### ISSUE TITLE
Extension is not allowed to make outbound calls with browser currently

### ISSUE THREAD

**Issue by nareshnootoo** [ringcentral/ringcentral-web-widget#16]
I am getting an error popup "Your extension is not allowed to make outbound calls with browser currently, please contact your account representative for an upgrade." Could anyone please explain what kind of issue is this?

**Comment by embbnux** [comment]
In web phone, it requires a DL in your extension account.

**Comment by nareshnootoo** [comment]
Hi, @embbnux thanks :+1:

**Comment by embbnux** [comment]
Welcome @nareshnootoo
