### ISSUE TITLE
Provide better error when Implicit Grant is not configured

### ISSUE THREAD

**Issue by grokify** [ringcentral/ringcentral-web-widget#23]
When the Web Widget is configured to use Implicit Grant (only `appKey` is passed) and the app (client Id) is not configured to support Implicit Grant in the Dev Portal (e.g. Auth Code only), clicking the widget "Sign In" button will cause the OAuth pop up to show up and disappear quickly with the following error:

![ringcentral error from widget cross domain error](https://user-images.githubusercontent.com/209872/31865946-60965ab4-b72c-11e7-99cc-23ec5b51096d.png)

`Unsafe JavaScript attempt to initiate navigation for frame with URL '' for frame with URL ''. The frame attempting navigation is neither same-origin with the target, nor is it the target's parent or opener.`

Add a more explicit error so developers can identify the issue more easily.

**Comment by embbnux** [comment]
Now app will show `unauthorized_client: The client is unauthorized for the required grant type: [IMPLICIT]` when app key without the required grant type
