### ISSUE TITLE
Listening to outboud call requests

### ISSUE THREAD

**Issue by AndyHaas** [ringcentral/ringcentral-web-widget#32]
When an inbound call comes in the rc-call-ring-notify and rc-call-end-notify get called and I can capture this via a event listnener. But when an outbound call goes out those two messages don't get called. So I started looking around and I find webphone-callStart. I try to listen for that event but I can't seem to get to it. 

So the question is can I listen for outbound calls same as inbound?

**Comment by embbnux** [comment]
Sorry, we haven't provide this API. We will add new API for it.
- [ ] add outbound call notification API

**Comment by embbnux** [comment]
Hi, @AndyHaas. Now you can listen for outbound calls on web widget.

**Comment by AndyHaas** [comment]
@embbnux this is indeed working. Just for anyone else here are the events that you need to listen to. The call start will be rc-call-start-notify and the end call will be the same as the incoming rc-call-end-notify
