### ISSUE TITLE
New Text and Messages

### ISSUE THREAD

**Issue by AndyHaas** [ringcentral/ringcentral-web-widget#44]
Suggestion is to have the messages link (envelope icon) also have compose new message at the bottom. Having 2 links at the top can miss lead people that there are 2 separate messaging ways.

**Comment by AndyHaas** [comment]
To add to this ticket when someone sends a text the text doesn't wrap it cuts off the word and puts it on a new line. If we can get it to word wrap then it would be easier to read. 
![messagenewline](https://user-images.githubusercontent.com/22582720/33029478-4c01ffa4-cdde-11e7-9d74-150695c571bb.JPG)

**Comment by embbnux** [comment]
Yeah, Two messages Icon will confuse user. Actually it has been in our backlog to improve this problem. 
And thanks for reporting the word wrap issue, we will fix it ASAP.
