### ISSUE TITLE
Keep the widget minimize state after page/tab refreshed

### ISSUE THREAD

**Issue by embbnux** [ringcentral/ringcentral-web-widget#48]
When user minimize the widget, it is better to keep this state unless user extends it even user refresh the page or go to new page.

**Comment by akolahi** [comment]
I would also suggest the placement of the widget also remain consistent across refresh or new pages.  Often users place the widget within a certain convenient location on the page.

**Comment by embbnux** [comment]
Thanks @akolahi Will add it

**Comment by embbnux** [comment]
@akolahi Now web widget supports to keep minimize and position state
