### ISSUE TITLE
Add in Voicemail tab

### ISSUE THREAD

**Issue by AndyHaas** [ringcentral/ringcentral-web-widget#49]
Add in a voicemail tab so the end user can listen to their voicemail.

Side note: be able to control what account the voicemail's are being retrieved from. For all users we would want them to pull the voicemail's from our main account number so they can listen to all the voicemail's our customer have left.

**Comment by embbnux** [comment]
Great Idea. Actually, it will come soon.

**Comment by embbnux** [comment]
Hi @AndyHaas Now the app supports to list voicemail in messages tab. Playing the voicemail will come soon.

**Comment by AndyHaas** [comment]
- [ ] Play voicemail on voicemail messages -> voicemail tab
