### ISSUE TITLE
Group Chat Reply Name and Group Contact Names

### ISSUE THREAD

**Issue by AndyHaas** [ringcentral/ringcentral-web-widget#54]
Under each person that replies it would be best to put who that person was. Also at the top instead of the extension numbers be able to do a contact lookup to resolve the name of the contact 

![image](https://user-images.githubusercontent.com/22582720/33445968-2edfb702-d5c4-11e7-86ac-01fc657a74b8.png)

**Comment by embbnux** [comment]
The feature is supported now.
