### ISSUE TITLE
Users getting logged out after an hour, even while on a call.

### ISSUE THREAD

**Issue by akolahi** [ringcentral/ringcentral-web-widget#63]
This issue was reported by some of our users:
'each hour they are using it it logs them out even if they are in the middle of a call.'

**Comment by AndyHaas** [comment]
please look at issue #31 . You have to change your app config to have the app key.

**Comment by embbnux** [comment]
Hi, @akolahi . Now in implicit grant flow, app doesn't support to refresh token. #8 
It's recommended to provide appSecret to this app. Provide it as appKey:

```
<script>
  (function() {
    var rcs = document.createElement("script");
    rcs.src = "https://ringcentral.github.io/ringcentral-web-widget/adapter.js?appKey=1111&appSecret=2222";
    var rcs0 = document.getElementsByTagName("script")[0];
    rcs0.parentNode.insertBefore(rcs, rcs0);
  })();
</script>
```

**Comment by akolahi** [comment]
Thank you. I've made the suggested change.

**Comment by embbnux** [comment]
Thanks @AndyHaas @akolahi for feedback
