### ISSUE TITLE
CRITICAL: Placing Call on Hold

### ISSUE THREAD

**Issue by AndyHaas** [ringcentral/ringcentral-web-widget#64]
When you place a call on hold and you come back to pick the call back up, the callers voice doesn't get transmitted over but the hold music does cut off on the receivers side and the receiver can talk and the caller can hear the receiver, but the caller can talk but the receiver can not hear the caller.

**Comment by embbnux** [comment]
Hi @AndyHaas I will look at it.

**Comment by embbnux** [comment]
Hi @AndyHaas  Would you please provide more information, such as browser version, network situation?  Actually, I can't reproduce this problem. Would you try it again?

**Comment by AndyHaas** [comment]
@embbnux I was not able to reproduce this morning. I will continue to test. 

Chrome 63.0.3239.87

**Comment by embbnux** [comment]
Thanks, @AndyHaas I think it was caused by unstable network. Web phone audio is based on WebRTC which dependent on stable network.

**Comment by AndyHaas** [comment]
Closing, until user can reduplicate, will troubleshoot further.
